name: ReactJS with GCP Pipeline

on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run eslint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

  build:
    needs: [format, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Upload build to GCS
        uses: google-github-actions/upload-gcs@v1
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
          bucket: your-gcs-bucket-name
          path: build
          gzip: true

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@releases/v11
        with:
          args: deploy --only hosting
          keyFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: your-firebase-project-id
