---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nftmusic-deployment
  labels:
    app: nftmusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nftmusic
  template:
    metadata:
      labels:
        app: nftmusic
    spec:
      containers:
        - name: nftmusic
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/nftmusic-app
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: nftmusic-service
spec:
  type: LoadBalancer
  selector:
    app: nftmusic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000