name: React JS Pipeline

on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Replace with your desired Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Format code
        run: npm run format # Replace with your formatting command if different

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Replace with your desired Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint # Replace with your linting command if different

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Replace with your desired Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test # Replace with your test command if different
        env:
          CI: true

  build:
    needs: [format, lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Replace with your desired Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build # Replace with your build command if different

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Firebase Hosting
        run: |
          npm install -g firebase-tools
          firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"

      # Alternatively, deploy to Google App Engine:
      # - name: Deploy to Google App Engine
      #   run: |
      #     gcloud app deploy app.yaml --version=${GITHUB_SHA} --project=${{ secrets.GCP_PROJECT_ID }}